### ISSUE TITLE
something wrong about HW3 

### ISSUE THREAD

**Issue by DoubleQiany** [courseworks/AUT_AP_2024_Spring_HW3#1]
the test.cpp file is empty

**Comment by smhamidi** [comment]
the tests will be added next week, until then you can test your code manually in the main.cpp file.
[smhamidi](https://github.com/smhamidi)

**Comment by Nana2929** [comment]
Dear sir, 
thank you for uploading the assignments, and I would like to know if it is possible to release the unit-test.cpp because it seems the test file is still empty.

**Comment by mango7789** [comment]
> the tests will be added next week, until then you can test your code manually in the main.cpp file. [smhamidi](https://github.com/smhamidi)

Hi Professor,

It seems that the `unit_test.cpp` file is still empty. Could you please check and update the file when you get a chance? Thanks in advance!
